### ISSUE TITLE
Тестовый сервер для передачи пачек билетов не работает 

### ISSUE THREAD

**Issue by Kelvin-Disando** [KosyanMedia/test-tasks#7]
Проблема с сервером, не отвечает уже второй день, невозможно выполнить тестовое задание aviasales_frontend. Почините пожалуйста, очень хочется попробовать свои силы ;)

**Comment by balozae** [comment]
@Kelvin-Disando поднял апишку
https://avs-backend.now.sh

те же функции/описание как в оригинальной задаче

* https://avs-backend.now.sh/search
* https://avs-backend.now.sh/tickets?searchId=...

шанс 1/6 что выпадет ошибка от сервера (502 код)

**Comment by Kelvin-Disando** [comment]
Очень круто!) Спасибо

**Comment by nikitabulatov** [comment]
@balozae Прикольно, что поднял свой сервер 😄

@Kelvin-Disando "Официальный" сервер для тестового задания теперь тоже работет. Сорри, что долго реагировали
