### ISSUE TITLE
Уточнение по фильтру

### ISSUE THREAD

**Issue by svetley1** [KosyanMedia/test-tasks#9]
В контексте билетов туда-обратно не понятно как делать фильтрацию.
~~Возможны следующие варианты:~~
1) ~~Отстаиваются билеты где **хотя бы один** segment не удовлетворяет фильтру~~
2) ~~Отсеиваются билеты где **оба** segment не удовлетворяют фильтру~~
3) ~~Отсеиваются билеты у которых **сумма** пересадок у segment-ов не удовлетворяют фильтру~~

ИМХО, это нужно уточнить в самом задании...

**Comment by svetley1** [comment]
Кажется правило должно звучать так: остаются лишь те билеты, в которых максимальное количество пересадок среди сегментов, не соответствует фильтру. 
Вроде бы так работает фильтр на aviasales.

**Comment by nikitabulatov** [comment]
Привет 👋 
Всё верно. Ответы на вопросы о реализации можно подсмотреть на нашем сайте.
В задании эта информация не указана умышленно :)
